<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection\Options\" />
    <Folder Include="UserCases\V1\Commands\Devices\" />
    <Folder Include="UserCases\V1\Queries\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StructureCodeSolution.Contract\StructureCodeSolution.Contract.csproj" />
    <ProjectReference Include="..\StructureCodeSolution.Domain\StructureCodeSolution.Domain.csproj" />
    <ProjectReference Include="..\StructureCodeSolution.Persistence\StructureCodeSolution.Persistence.csproj" />
  </ItemGroup>

</Project>
