<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DependencyInjection\Options\**" />
    <Compile Remove="Usecases\V1\Commands\Devices\**" />
    <Compile Remove="UserCases\**" />
    <Compile Remove="Validators\**" />
    <EmbeddedResource Remove="DependencyInjection\Options\**" />
    <EmbeddedResource Remove="Usecases\V1\Commands\Devices\**" />
    <EmbeddedResource Remove="UserCases\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="DependencyInjection\Options\**" />
    <None Remove="Usecases\V1\Commands\Devices\**" />
    <None Remove="UserCases\**" />
    <None Remove="Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Usecases\V1\Commands\Devices\Abstracts\Command.cs" />
    <Compile Include="Usecases\V1\Commands\Devices\CreateDeviceCommandHandler.cs" />
    <Compile Include="Usecases\V1\Commands\Devices\Validators\CreateDeviceValidator.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StructureCodeSolution.Domain\StructureCodeSolution.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Usecases\V1\Products\Queries\" />
  </ItemGroup>

</Project>
