<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\StructureCodeSolution.Application\StructureCodeSolution.Application.csproj" />
    <ProjectReference Include="..\..\Core\StructureCodeSolution.Contract\StructureCodeSolution.Contract.csproj" />
    <ProjectReference Include="..\..\Core\StructureCodeSolution.Domain\StructureCodeSolution.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\StructureCodeSolution.Infrastructure.MessageBus\StructureCodeSolution.Infrastructure.MessageBus.csproj" />
    <ProjectReference Include="..\..\Infrastructure\StructureCodeSolution.Infrastructure\StructureCodeSolution.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\StructureCodeSolution.Persistence\StructureCodeSolution.Persistence.csproj" />
  </ItemGroup>

</Project>
